# Disclaimer: This file was generated by AI.
# It contains logic for plotting GEMM benchmarking results.

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def plot_latency(csv_file: str | Path, out_dir: str | Path | None = None) -> None:
    """
    Plots the latency (time in ms) for different implementations from a CSV file.
    """
    csv_path = Path(csv_file)
    if not out_dir:
        out_dir = csv_path.parent
    else:
        out_dir = Path(out_dir)

    out_dir.mkdir(parents=True, exist_ok=True)

    # Read the benchmarking results
    df = pd.read_csv(csv_path)

    # Create the plot
    plt.figure(figsize=(10, 6))
    bars = plt.bar(df["name"], df["time(ms)"], color="skyblue")

    # Add labels and title
    plt.ylabel("Time (ms)")
    plt.xlabel("Implementation")
    plt.title(f"GEMM Latency Comparison ({csv_path.stem})")
    plt.xticks(rotation=45)

    # Add value labels on top of bars
    for bar in bars:
        yval = bar.get_height()
        plt.text(
            bar.get_x() + bar.get_width() / 2,
            yval,
            f"{yval:.4f}",
            va="bottom",
            ha="center",
        )

    plt.tight_layout()

    # Save the plot
    out_file = out_dir / f"{csv_path.stem}_latency.png"
    plt.savefig(out_file)
    plt.close()


def plot_performance(csv_file: str | Path, out_dir: str | Path | None = None) -> None:
    """
    Plots the performance (GFLOPS) for different implementations from a CSV file.
    """
    csv_path = Path(csv_file)
    if not out_dir:
        out_dir = csv_path.parent
    else:
        out_dir = Path(out_dir)

    out_dir.mkdir(parents=True, exist_ok=True)

    # Read the benchmarking results
    df = pd.read_csv(csv_path)

    # Create the plot
    plt.figure(figsize=(10, 6))
    bars = plt.bar(df["name"], df["perf(GFLOPS)"], color="salmon")

    # Add labels and title
    plt.ylabel("Performance (GFLOPS)")
    plt.xlabel("Implementation")
    plt.title(f"GEMM Performance Comparison ({csv_path.stem})")
    plt.xticks(rotation=45)

    # Add value labels on top of bars
    for bar in bars:
        yval = bar.get_height()
        plt.text(
            bar.get_x() + bar.get_width() / 2,
            yval,
            f"{yval:.2f}",
            va="bottom",
            ha="center",
        )

    plt.tight_layout()

    # Save the plot
    out_file = out_dir / f"{csv_path.stem}_perf.png"
    plt.savefig(out_file)
    plt.close()


if __name__ == "__main__":
    if len(sys.argv) == 3:
        plot_latency(sys.argv[1], sys.argv[2])
        plot_performance(sys.argv[1], sys.argv[2])
    elif len(sys.argv) == 2:
        plot_latency(sys.argv[1])
        plot_performance(sys.argv[1])
    else:
        print(f"Usage: {sys.argv[0]} <csv_file> [out_dir]")
